---
layout: post
category: ecology
tags: warning-signals

---

```{r, include=FALSE, echo=FALSE, cache=FALSE}
opts_knit$set(upload.fun = socialR::notebook.url)
opts_chunk$set(dev.args=list(bg="transparent"), comment=NA, tidy=FALSE, cache=TRUE, 
               warnings=FALSE, messages=FALSE, 
               cache.path="~/Documents/data/2012-12-17-ews-example")
require(ggplot2)
theme_set(theme_bw())
theme_update(panel.background = element_rect(fill = "transparent", colour = NA),
             plot.background = element_rect(fill = "transparent", colour = NA))
```


ENSO EWS
========================================================

Let's just see what happens with the [MEI data](http://www.esrl.noaa.gov/psd/enso/mei/) for PDO:

```{r}
dat <- read.table("http://carlboettiger.info/assets/data/mei.csv", header=TRUE)
```

```{r, results="asis"}
print(xtable::xtable(head(dat)), type="html")
```

For the moment let's ignore annual structure and just collapse this into timeseries sampled bimonthly.  

```{r}
require(reshape2)
dt <- melt(dat, id="YEAR")
X <- dt$value
Z <- X[!is.na(X)]
Z <- data.frame(1:(length(Z)-1), Z[1:(length(Z)-1)])
```



```{r cache=FALSE}
library(earlywarning)
library(snow)
library(methods)
cl <- makeCluster(16, type="MPI")
clusterEvalQ(cl, library(earlywarning))
````

```{r }
data(ibms)
A <- stability_model(Z, "OU")
B <- stability_model(Z, "LSN")
observed <- -2 * (logLik(A) - logLik(B))
````

```{r }
clusterExport(cl, ls())
clusterExport(cl, list = c("A", "B"))
reps <- parLapply(cl, 1:500, function(i) compare(A,B))
lr <- lik_ratios(reps)
roc <- roc_data(lr)
````

```{r }
save(list=ls(), file="simulation.rda")
stopCluster(cl)
````

```{r } 
require(ggplot2)
ggplot(lr) + geom_density(aes(value, fill=simulation), alpha=0.6) + geom_vline(aes(xintercept=observed))
```

```{r }
ggplot(roc) + geom_line(aes(False.positives, True.positives))
````