---
layout: post
categories:
- ecology
- open-science
tags: 
- semantics
- nonparametric-bayes
---

`r library(knitcitations); cite_options(tooltip=TRUE)`

## Meeting with Marc

selection of problem: consider simpler models only.  

step through complexity hierarchy at the beginning

  1. classical approaches are to fix relationship of stock recruitment.  
  2. parameter uncertainty
  3. Gaussian processes for model uncertainty

The Discussion section can deal with model uncertainty model choice approaches.  

  * A method where we don't have to assume the stock recuritment relationship
  * How well we can do with that.  
  * How much data we need.  

discussion of mathematical presentation, clarity



## Misc

* Finished review.  I should stop signing reviews, then I could write more careless quick impressions.  
* discussed potential of a GSOC proposal for an R NEXML parser
* requested to consider presenting at [ISI Conference](http://isiconference2013.org/pgs/specsessions.php) session on early warning.  



## some reading on semantics

David Shotton and Tanya Gray have release a CiTO tool for adding semantic data to many major publication platforms, taking a clever approach to annotation that I've never considered -- croudsourcing to readers `r citep("http://semanticpublishing.wordpress.com/2013/02/26/cito-tools/", "discusses")`.  The tool isn't perfect but is very intuitive.  The clever part is that all annotations the reader adds are collated in a database and cand be retrieved through their [API](http://www.miidi.org/cito/api/). Not sure if many readers will make use of this, but time will tell. Meanwhile authors or publishers might pay attention.   

In that vein, David has also written a call of Ten Next Steps for publishers, `r citep("http://semanticpublishing.wordpress.com/2013/02/26/ten-next-steps", "discusses")`.  Some may be redundant, but certainly shows how publishers could go a lot further.  If only there was more incentive for publishers to innovate like this instead of crafting clever and questionable strategies to boost impact factors.  


## Reading

Very interesting paper on implementing/teaching nonlinear model inference to ecologists out today `r citep("10.1111/2041-210X.12044", "discusses")`, and the [code and data for each of the examples they discuss](https://groups.nceas.ucsb.edu/non-linear-modeling/projects).  Lessons in the mansucript may be familiar to many, but should still be taught more widely in ecology. Should be useful for teaching this stuff in graduate courses too.  



```{r results="asis"}
bibliography()
```



