---
layout: post
published: false
---


Knitr allows us to write dynamic documents that combine code with text.  Though the idea is quite simple, implementation into an active research workflow that moves from development of ideas, through running diverse analyses on large remote servers, to writing and revising a manuscript can be non-trivial.  

The basic idea of the dynamic document is to replace lines of text that report results, such as figures, tables, or in-text parameter values with the code that generates them.  It's arguably a matter of taste (see [Literate Programming]()) whether the code literally resides in the text document or is sourced in from the appropriate external files (in any event it will rely on external code provided by software libraries, etc).  The point is that results and figures are not manually copied over, which could allow the mansucript to get out of sync with the analysis, or could introduce copying errors.  This approach is also believed to help provide (guarentee is too strong, as errors are still possible) _reproducible_ results `r citep("10.1126/science.1213847", "citesAsEvidence")` [^1].  

## Manuscript challenges

While developing my analysis, I find it useful to intersperse textual descriptions, often with equations and citations, in between the steps of my analysis represented as code chunks.  When actually presenting how to computationally implement a procedure, I prefer code chunks that are as small as possible, are without code comments (as explanation should appear in the plain text) and use names for functions and variables that define their meaning or otherwise correspond directly to equations in the text.  With high level functional scripting languages like R, there is little reason for a manuscript to prevent pseudo-code in place of real code.  


When writing the manuscript, the presentation of an analysis does not often follow the presentation of the methodology -- sometimes I want to present results before methods, or present a summary of methods while differing detailed presentation to the end. Almost always I want to supress the code display itself, or code blocks only in the appendix.  I've struggled to convince myself that a carefully crafted dynamic document could get around this and all I would have to do to transition from an analysis script to the manuscript would be to toggle `opts_chunk$set(echo=FALSE)` to supress printing of the code. In practice, I nearly always end up writing or sourcing in all the analysis at the top of the manuscript file, and then simply importing figures, tables, and results values with codeblocks where I want them.  

Figures still benefit from the dynamic context


### gotchas 

we can't toggle global chunk and keep cache




[^1]: This follows the definition of Roger Peng, `r citep("10.1126/science.1213847", "citesAsEvidence")` in which sense computationally reproducible is a weaker version of _replicable_.  Reproducible means only that we can run the code provided and reproduce the same results, whereas replication implies the scientific gold standard of replicating the results from scratch. 
